In [1]:
class Config:
    def __init__(self):
        self.mode = 'train'
        self.small = False
        self.train_dir = "/home/angrypark/data/abusive_text_detection/ilbe/train.txt"
        self.val_dir = "/home/angrypark/data/abusive_text_detection/ilbe/test.txt"
        self.pretrained_embed_dir = ""
        self.model = "TextCNN"
        self.normalizer = "BasicNormalizer"
        self.tokenizer = "SyllableTokenizer"
        self.vectorizer = "DummyVectorizer"
        self.vocab_size = 20000
        self.embed_dim = 128
        self.min_length = 5
        self.max_length = 50
        self.filter_sizes = "3,4,5"
        self.num_filters = 128
        self.dropout_keep_prob = 0.9
        self.l2_reg_lambda = 0.0
        self.batch_size = 64
        self.num_epochs = 5
        self.evaluate_every = 1
        self.checkpoint_every = 1
        self.allow_soft_replacement = True
        self.log_device_placement = False
        self.shuffle = False
        self.pretrained_embed_dir = "/home/angrypark/data/fasttext/fasttext.200M.256D.npy"

In [2]:
config = Config()

In [5]:
from data_loader import DataGenerator
from models import TextCNN
from trainer import Trainer
from preprocessor import Preprocessor
from utils.dirs import create_dirs
from utils.logger import Logger

In [6]:
preprocessor = Preprocessor(config)

In [7]:
data = DataGenerator(preprocessor, config)

100%|██████████| 7601/7601 [00:00<00:00, 667690.89it/s]

Build Vocabulary...


Vocabulary Built. Total number of unique tokens :  1662


In [8]:
i = 0
for x_batch, y_batch in data.next_batch(32):
    if i==0:
        x = x_batch
        y = y_batch
    i+=1

In [9]:
x

array([[ 911,  406,  270, ...,    0,    0,    0],
       [ 771,  950, 1163, ...,    0,    0,    0],
       [ 652, 1036,    4, ...,    0,    0,    0],
       ...,
       [ 240,  347,    4, ...,    0,    0,    0],
       [1300, 1300,    4, ...,    0,    0,    0],
       [ 651, 1232,    4, ...,    0,    0,    0]], dtype=int32)

In [10]:
y

array([0, 1, 0, 0, 1, 0, 2, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0,
       0, 0, 0, 0, 2, 0, 2, 0, 0, 0])

In [12]:
import numpy as np
np.array([[1],[2]])

array([[1],
       [2]])

In [44]:
predictions = np.load("predictions.npy")

In [45]:
scores = np.load("scores.npy")

In [46]:
for i in range(len(predictions)):
    if predictions[i]!=0:
        print(predictions[i])

In [48]:
for i in range(len(predictions)):
    if np.argmax(scores[i])!=0:
        print(np.argmax(scores[i]))

In [49]:
with open("/home/angrypark/data/abusive_text_detection/ilbe/test.txt", 'r') as f:
    val_data, val_labels = zip(*[line.split('\t') for line in f])
    val_labels = [int(i.strip()) for i in val_labels]

In [50]:
sum([x==y for x, y in zip(val_labels, predictions)])/len(val_labels)

0.7242603550295857

In [51]:
from collections import Counter
Counter(val_labels)

Counter({0: 612, 1: 119, 2: 114})

In [52]:
Counter(predictions)

Counter({0: 845})

In [55]:
len(x[0])

50